<?php
/*************************************************************************************************************************
**************************************************************************************************************************
**************************************************************************************************************************

WARNING!!!

THIS FILE SHOULD NOT BE EDITED - IT WILL BE AUTOGENERATED EACH TIME THE MODELS ARE BUILT!

OVERRIDE SETTINGS IN MODEL NOT THE BASEMODEL

**************************************************************************************************************************
**************************************************************************************************************************
*************************************************************************************************************************/

namespace project\db\om\nanophp\base;

/**
 * BaseUserTable class 
 * 
 * BaseUserTable
 * 
 * @author Christopher Beck <cwbeck@gmail.com>
 * @version SVN: $id
 * @package nanophp
 * @subpackage base
 */
class BaseUserTable extends \nano\core\db\om\BaseTable {

	protected $modelName = 'User';
	protected $primaryKey = array('id');
	protected $dbConfig = 'default';
	protected $dbName = 'nanophp';
	protected $tableName = 'Users';
	protected $fields = array(
		'id' => array(
			'mysql_type' => 'int(11)',
			'mysql_is_null' => 'NO',
			'mysql_key' => 'PRI',
			'mysql_default' => '',
			'mysql_extra' => 'auto_increment',
			'is_foreign_reference' => false,
			'use_model' => 'User',
			'use_database' => 'nanophp',
			'set_function' => 'setId',
			'validation_function' => 'validateId',
			'get_function' => 'getId',
		),
		'language' => array(
			'mysql_type' => 'char(7)',
			'mysql_is_null' => 'NO',
			'mysql_key' => '',
			'mysql_default' => '',
			'mysql_extra' => '',
			'is_foreign_reference' => false,
			'use_model' => 'User',
			'use_database' => 'nanophp',
			'set_function' => 'setLanguage',
			'validation_function' => 'validateLanguage',
			'get_function' => 'getLanguage',
		),
		'email' => array(
			'mysql_type' => 'varchar(255)',
			'mysql_is_null' => 'NO',
			'mysql_key' => 'MUL',
			'mysql_default' => '',
			'mysql_extra' => '',
			'is_foreign_reference' => false,
			'use_model' => 'User',
			'use_database' => 'nanophp',
			'set_function' => 'setEmail',
			'validation_function' => 'validateEmail',
			'get_function' => 'getEmail',
		),
		'password' => array(
			'mysql_type' => 'varchar(255)',
			'mysql_is_null' => 'NO',
			'mysql_key' => '',
			'mysql_default' => '',
			'mysql_extra' => '',
			'is_foreign_reference' => false,
			'use_model' => 'User',
			'use_database' => 'nanophp',
			'set_function' => 'setPassword',
			'validation_function' => 'validatePassword',
			'get_function' => 'getPassword',
		),
		'is_active' => array(
			'mysql_type' => 'tinyint(1)',
			'mysql_is_null' => 'NO',
			'mysql_key' => '',
			'mysql_default' => '0',
			'mysql_extra' => '',
			'is_foreign_reference' => false,
			'use_model' => 'User',
			'use_database' => 'nanophp',
			'set_function' => 'setIsActive',
			'validation_function' => 'validateIsActive',
			'get_function' => 'getIsActive',
		),
		'is_admin' => array(
			'mysql_type' => 'tinyint(1)',
			'mysql_is_null' => 'NO',
			'mysql_key' => '',
			'mysql_default' => '0',
			'mysql_extra' => '',
			'is_foreign_reference' => false,
			'use_model' => 'User',
			'use_database' => 'nanophp',
			'set_function' => 'setIsAdmin',
			'validation_function' => 'validateIsAdmin',
			'get_function' => 'getIsAdmin',
		),
		'is_super_admin' => array(
			'mysql_type' => 'tinyint(1)',
			'mysql_is_null' => 'NO',
			'mysql_key' => '',
			'mysql_default' => '0',
			'mysql_extra' => '',
			'is_foreign_reference' => false,
			'use_model' => 'User',
			'use_database' => 'nanophp',
			'set_function' => 'setIsSuperAdmin',
			'validation_function' => 'validateIsSuperAdmin',
			'get_function' => 'getIsSuperAdmin',
		),
		'created_at' => array(
			'mysql_type' => 'datetime',
			'mysql_is_null' => 'NO',
			'mysql_key' => '',
			'mysql_default' => '',
			'mysql_extra' => '',
			'is_foreign_reference' => false,
			'use_model' => 'User',
			'use_database' => 'nanophp',
			'set_function' => 'setCreatedAt',
			'validation_function' => 'validateCreatedAt',
			'get_function' => 'getCreatedAt',
		),
		'updated_at' => array(
			'mysql_type' => 'datetime',
			'mysql_is_null' => 'NO',
			'mysql_key' => '',
			'mysql_default' => '',
			'mysql_extra' => '',
			'is_foreign_reference' => false,
			'use_model' => 'User',
			'use_database' => 'nanophp',
			'set_function' => 'setUpdatedAt',
			'validation_function' => 'validateUpdatedAt',
			'get_function' => 'getUpdatedAt',
		)
	);
	protected $newFieldNameMap = array(
		'id' => 'id',
		'language' => 'language',
		'email' => 'email',
		'password' => 'password',
		'is_active' => 'is_active',
		'is_admin' => 'is_admin',
		'is_super_admin' => 'is_super_admin',
		'created_at' => 'created_at',
		'updated_at' => 'updated_at'
	);

	public function retrieveByPk($id) {
		$query = new \nano\core\db\core\SelectQuery();
		$query->from('Users')->where('`Users`.`id` = "'.addslashes($id).'" LIMIT 1');
		$results = $this->doSelect($query);
		return isset($results[0]['User'])? $results[0]['User'] : null;
	}

}