<?php
/*************************************************************************************************************************
**************************************************************************************************************************
**************************************************************************************************************************

WARNING!!!

THIS FILE SHOULD NOT BE EDITED - IT WILL BE AUTOGENERATED EACH TIME THE MODELS ARE BUILT!

OVERRIDE SETTINGS IN MODEL NOT THE BASEMODEL

**************************************************************************************************************************
**************************************************************************************************************************
*************************************************************************************************************************/

namespace project\db\om\nanophp\base;

/**
 * BaseSession class 
 * 
 * BaseSession
 * 
 * @author Christopher Beck <cwbeck@gmail.com>
 * @version SVN: $id
 * @package nanophp
 * @subpackage base
 */
class BaseSession extends \nano\core\db\om\Base {

	protected $modelName = 'Session';
	protected $primaryKey = array('id');
	protected $dbConfig = 'default';
	protected $dbName = 'nanophp';
	protected $tableName = 'Sessions';
	protected $fields = array(
		'id' => array(
			'mysql_type' => 'int(11)',
			'mysql_is_null' => 'NO',
			'mysql_key' => 'PRI',
			'mysql_default' => '',
			'mysql_extra' => 'auto_increment',
			'is_foreign_reference' => false,
			'use_model' => 'Session',
			'use_database' => 'nanophp',
			'set_function' => 'setId',
			'validation_function' => 'validateId',
			'get_function' => 'getId',
		),
		'User' => array(
			'mysql_type' => 'int(11)',
			'mysql_is_null' => 'NO',
			'mysql_key' => '',
			'mysql_default' => '',
			'mysql_extra' => '',
			'is_foreign_reference' => true,
			'use_model' => 'User',
			'use_database' => 'nanophp',
			'set_function' => 'setUser',
			'validation_function' => 'validateUser',
			'get_function' => 'getUser',
		),
		'token' => array(
			'mysql_type' => 'char(255)',
			'mysql_is_null' => 'NO',
			'mysql_key' => 'MUL',
			'mysql_default' => '',
			'mysql_extra' => '',
			'is_foreign_reference' => false,
			'use_model' => 'Session',
			'use_database' => 'nanophp',
			'set_function' => 'setToken',
			'validation_function' => 'validateToken',
			'get_function' => 'getToken',
		),
		'ip' => array(
			'mysql_type' => 'int(11)',
			'mysql_is_null' => 'NO',
			'mysql_key' => '',
			'mysql_default' => '',
			'mysql_extra' => '',
			'is_foreign_reference' => false,
			'use_model' => 'Session',
			'use_database' => 'nanophp',
			'set_function' => 'setIp',
			'validation_function' => 'validateIp',
			'get_function' => 'getIp',
		),
		'created' => array(
			'mysql_type' => 'datetime',
			'mysql_is_null' => 'NO',
			'mysql_key' => '',
			'mysql_default' => '',
			'mysql_extra' => '',
			'is_foreign_reference' => false,
			'use_model' => 'Session',
			'use_database' => 'nanophp',
			'set_function' => 'setCreated',
			'validation_function' => 'validateCreated',
			'get_function' => 'getCreated',
		)
	);
	protected $newFieldNameMap = array(
		'id' => 'id',
		'User' => 'User',
		'token' => 'token',
		'ip' => 'ip',
		'created' => 'created'
	);
	public function setId($value){
		if(\project\db\om\nanophp\Session::validateId($value)){
			$this->id = $value;
		} else {
			throw new \nano\core\exception\ValidationException('Validation of column `id` failed');
		}
	}
	public function setUser($value){
		if(\project\db\om\nanophp\Session::validateUser($value)){
			$this->User = $value;
		} else {
			throw new \nano\core\exception\ValidationException('Validation of column `User` failed');
		}
	}
	public function setToken($value){
		if(\project\db\om\nanophp\Session::validateToken($value)){
			$this->token = $value;
		} else {
			throw new \nano\core\exception\ValidationException('Validation of column `token` failed');
		}
	}
	public function setIp($value){
		if(\project\db\om\nanophp\Session::validateIp($value)){
			$this->ip = $value;
		} else {
			throw new \nano\core\exception\ValidationException('Validation of column `ip` failed');
		}
	}
	public function setCreated($value){
		if(\project\db\om\nanophp\Session::validateCreated($value)){
			$this->created = $value;
		} else {
			throw new \nano\core\exception\ValidationException('Validation of column `created` failed');
		}
	}
	public function getId(){
		return $this->id;
	}
	public function getUser(){
		return $this->User;
	}
	public function getToken(){
		return $this->token;
	}
	public function getIp(){
		return $this->ip;
	}
	public function getCreated(){
		return $this->created;
	}
	public static function validateId($value){
		return true;
	}
	public static function validateUser($value){
		return true;
	}
	public static function validateToken($value){
		return true;
	}
	public static function validateIp($value){
		return true;
	}
	public static function validateCreated($value){
		return true;
	}
	
}