<?php
/*************************************************************************************************************************
**************************************************************************************************************************
**************************************************************************************************************************

WARNING!!!

THIS FILE SHOULD NOT BE EDITED - IT WILL BE AUTOGENERATED EACH TIME THE MODELS ARE BUILT!

OVERRIDE SETTINGS IN MODEL NOT THE BASEMODEL

**************************************************************************************************************************
**************************************************************************************************************************
*************************************************************************************************************************/

namespace project\db\om\nanophp\base;

/**
 * BaseSessionTable class 
 * 
 * BaseSessionTable
 * 
 * @author Christopher Beck <chris.beck@jpmh.co.uk>
 * @version SVN: $id
 * @package nanophp
 * @subpackage base
 */
class BaseSessionTable extends \nano\core\db\om\BaseTable {

	protected $modelName = 'Session';
	protected $primaryKey = array('id');
	protected $dbConfig = 'default';
	protected $dbName = 'nanophp';
	protected $tableName = 'Sessions';
	protected $fields = array(
		'id' => array(
			'mysql_type' => 'int(11)',
			'mysql_is_null' => 'NO',
			'mysql_key' => 'PRI',
			'mysql_default' => '',
			'mysql_extra' => 'auto_increment',
			'is_foreign_reference' => false,
			'use_model' => 'Session',
			'use_database' => 'nanophp',
			'set_function' => 'setId',
			'validation_function' => 'validateId',
			'get_function' => 'getId',
		),
		'User' => array(
			'mysql_type' => 'int(11)',
			'mysql_is_null' => 'NO',
			'mysql_key' => '',
			'mysql_default' => '',
			'mysql_extra' => '',
			'is_foreign_reference' => true,
			'use_model' => 'User',
			'use_database' => 'nanophp',
			'set_function' => 'setUser',
			'validation_function' => 'validateUser',
			'get_function' => 'getUser',
		),
		'token' => array(
			'mysql_type' => 'char(255)',
			'mysql_is_null' => 'NO',
			'mysql_key' => 'MUL',
			'mysql_default' => '',
			'mysql_extra' => '',
			'is_foreign_reference' => false,
			'use_model' => 'Session',
			'use_database' => 'nanophp',
			'set_function' => 'setToken',
			'validation_function' => 'validateToken',
			'get_function' => 'getToken',
		),
		'ip' => array(
			'mysql_type' => 'int(11)',
			'mysql_is_null' => 'NO',
			'mysql_key' => '',
			'mysql_default' => '',
			'mysql_extra' => '',
			'is_foreign_reference' => false,
			'use_model' => 'Session',
			'use_database' => 'nanophp',
			'set_function' => 'setIp',
			'validation_function' => 'validateIp',
			'get_function' => 'getIp',
		),
		'created' => array(
			'mysql_type' => 'datetime',
			'mysql_is_null' => 'NO',
			'mysql_key' => '',
			'mysql_default' => '',
			'mysql_extra' => '',
			'is_foreign_reference' => false,
			'use_model' => 'Session',
			'use_database' => 'nanophp',
			'set_function' => 'setCreated',
			'validation_function' => 'validateCreated',
			'get_function' => 'getCreated',
		)
	);
	protected $newFieldNameMap = array(
		'id' => 'id',
		'User' => 'User',
		'token' => 'token',
		'ip' => 'ip',
		'created' => 'created'
	);

	public function retrieveByPk($id) {
		$query = new \nano\core\db\core\SelectQuery();
		$query->from('Sessions')->where('`Sessions`.`id` = "'.addslashes($id).'" LIMIT 1');
		$results = $this->doSelect($query);
		return isset($results[0]['Session'])? $results[0]['Session'] : null;
	}

}