<?php
/*************************************************************************************************************************
**************************************************************************************************************************
**************************************************************************************************************************

WARNING!!! - THIS FILE SHOULD NOT BE EDITED - IT WILL BE AUTOGENERATED EACH TIME THE MODELS ARE BUILT!

**************************************************************************************************************************
**************************************************************************************************************************
*************************************************************************************************************************/
namespace project\db\om\nanophp\map;

/**
 * Map class 
 * 
 * Map
 * 
 * @author Christopher Beck <cwbeck@gmail.com>
 * @version SVN: $id
 * @package nanophp
 * @subpackage templates
 */
class Map {
	public static $tableNameToModelName = array(
		'Auths' => 'Auth',
		'Languages' => 'Language',
		'Sessions' => 'Session',
		'Users' => 'User'
	);
	public static $modelNameToTableName = array(
		'Auth' => 'Auths',
		'Language' => 'Languages',
		'Session' => 'Sessions',
		'User' => 'Users'
	);
	public static $mapTablesToColumns = array(
		'Auths' => array('id' => 'id','type' => 'type','uid' => 'uid','fuid' => 'fuid','perams' => 'perams'),
		'Languages' => array('code' => 'code','key' => 'key','value' => 'value'),
		'Sessions' => array('id' => 'id','User' => 'User','token' => 'token','ip' => 'ip','created' => 'created'),
		'Users' => array('id' => 'id','language' => 'language','email' => 'email','password' => 'password','is_active' => 'is_active','is_admin' => 'is_admin','is_super_admin' => 'is_super_admin','created_at' => 'created_at','updated_at' => 'updated_at')
	);

	public static function getModelNameFromTableName($tableName){
		return isset(self::$tableNameToModelName[$tableName])? self::$tableNameToModelName[$tableName] : null;
	}
	
	public static function getTableNameFromModelName($modelName){
		return isset(self::$modelNameToTableName[$modelName])? self::$modelNameToTableName[$modelName] : null;
	}
}