<?php
/*************************************************************************************************************************
**************************************************************************************************************************
**************************************************************************************************************************

WARNING!!! - THIS FILE SHOULD NOT BE EDITED - IT WILL BE AUTOGENERATED EACH TIME THE MODELS ARE BUILT!

**************************************************************************************************************************
**************************************************************************************************************************
*************************************************************************************************************************/
namespace project\db\om\{{ database }}\map;

/**
 * Map class 
 * 
 * Map
 * 
 * @author Christopher Beck <cwbeck@gmail.com>
 * @version SVN: $id
 * @package {{ database }}
 * @subpackage templates
 */
class Map {
{{ classBody }}
	public static function getModelNameFromTableName($tableName){
		return isset(self::$tableNameToModelName[$tableName])? self::$tableNameToModelName[$tableName] : null;
	}
	
	public static function getTableNameFromModelName($modelName){
		return isset(self::$modelNameToTableName[$modelName])? self::$modelNameToTableName[$modelName] : null;
	}
}